/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BottomBar: typeof import('./src/components/BottomBar.vue')['default']
    CenterPanel: typeof import('./src/components/CenterPanel/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
